mass = 0.2
prop_thrust_coeff = 0.00001
prop_moment_coeff = 0.00000001
prop_max_omega = 400.0
prop_max_omega_dot = 1600.0
propeller_diameter = 0.275
minimum_drag_coeff = 0.2
maximum_drag_coeff = 3.35
roll_rate_drag_coeff = 0.05
pitch_rate_drag_coeff = 0.025
yaw_rate_drag_coeff = 0.005
linear_elevon_effectiveness = [0.0, 0.33, 0.0]
rotational_elevon_effectiveness = [0.0, -1.69, 0.0]
max_elevon_angle = 0.524
max_elevon_angle_dot = 21.0
wingspan = 0.55
chord = 0.15
depth = 0.01
elevon_percentage = 0.5
delta_r = 0.015
propeller_moment_arm_left = [0.0, -0.1375, 0.0]
propeller_moment_arm_right = [0.0, 0.1375, 0.0]