pos_x = 0.0
pos_y = 0
pos_z = 0
vel_x_body = 0
vel_y_body = 0
vel_z_body = 0
roll = 0
pitch = 90
yaw = 0
omega_x = 0
omega_y = 0
omega_z = 0
elevon_left = 0
elevon_right = 0
motor_omega_left = -285
motor_omega_right = 285