pos_x = 0.0
pos_y = 15.88727255682359
pos_z = 0.13019
vel_x_body = 6.12943
vel_y_body = -0.07052
vel_z_body = 1.16154
roll = -14.939109536661162
pitch = 10.90313266791506
yaw = 0.0
omega_x = 0.07177
omega_y = 0.10124
omega_z = -0.37258
elevon_left = -4.6433015379417535
elevon_right = -4.7249308350140415
motor_omega_left = -183.998
motor_omega_right = 182.427